server:
  port: ${SERVER_PORT:8004}

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://ticket_mongo:ticket_mongo_pw@localhost:27017/notification_db?authSource=admin}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: health,info
